############################################################
#
# Home Assistant Main Configuration File
#
############################################################
homeassistant:
  name: Conure Nest
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: imperial
  time_zone: MST
  customize: !include_dir_merge_named customize 

#introduction:
frontend:
updater:
discovery:
conversation:
history:
sun:
logbook:

############################################################
#
# Components
#
############################################################

            
device_tracker:
  - platform: owntracks
    hosts: '10.10.128.0/24'
    home_interval: 10

light:
  platform: hue 
  friendly_name: "Phillips Hue Lights"
  host: '10.10.128.128'
    
mqtt:
  broker: !secret mqtt_broker_ip
  port: !secret mqtt_port
  client_id: !secret mqtt_client_id
  keepalive: 60
  username: !secret mqtt_username 
  password: !secret mqtt_password 

# Example configuration.yaml entry
mqtt_eventstream:
  publish_topic: /home-assistant-1
  subscribe_topic: /home-assistant-slave


media_player:
  - platform: plex
  
 
sensor:
  - platform: yr
  
tts:
  platform: google

############################################################
#
# Includes
#
############################################################

automation: !include_dir_merge_list automation
switch: !include_dir_merge_list switches
group: !include_dir_merge_named groups


