############################################################
#
# Home Assistant Main Configuration File
#
############################################################
homeassistant:
  name: Conure Nest
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: imperial
  time_zone: MST
  customize: !include_dir_merge_named customize 

#introduction:
frontend:
updater:
discovery:
conversation:
history:
sun:
logbook:
recorder:
  purge_days: 3

############################################################
#
# Components
#
############################################################


            
device_tracker:
  - platform: owntracks
    hosts: '10.10.128.0/24'
    home_interval: 10

light:
  platform: hue 
  friendly_name: "Phillips Hue Lights"
  host: '10.10.128.128'
    
mqtt:
  broker: !secret mqtt_broker_ip
  port: !secret mqtt_port
  client_id: !secret mqtt_client_id
  keepalive: 60
  username: !secret mqtt_username 
  password: !secret mqtt_password 

# Example configuration.yaml entry
mqtt_eventstream:
  publish_topic: /home-assistant-1
  subscribe_topic: /home-assistant-slave

http:
  # Uncomment this to add a password (recommended!)
#   api_password: xxxxx
   # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

influxdb:
  host: 127.0.0.1
  #port: 8086
  database: homeassistant


# mysensors:
  # gateways:
    # - device: mqtt
      # persistence_file: '/home/homeassistant/.homeassistant/mysensors1.json'
      # topic_in_prefix: '/house/external/garage/GD1'
      # topic_out_prefix: '/house/external/garage/GD1'
  # debug: true
  # optimistic: false
  # persistence: true
  # retain: true
  # version: 2.0
 

  
# nest:
  # client_id: a1251e40-965b-4b6b-a3d2-e43a8b6ac488
  # client_secret: Z4V5kWesWRcDqqlW9LuxMdk9y
  # structure:
    # - Primary
  
# media_player:
  # - platform: plex


# camera:
  # platform: mjpeg
  # name: "Garage Camera"
  # image_width: 640
  # image_height: 480
  # image_quality: 7
  # mjpeg_url: http://10.10.128.159:8082


  
tts:
  platform: google

############################################################
#
# Includes
#
############################################################

automation: !include_dir_merge_list automation
cover: !include_dir_merge_list cover
group: !include_dir_merge_named groups
switch: !include_dir_merge_list switches
sensor: !include_dir_merge_list sensor


################################################
## Component Includes (Merge Named)
################################################

# input_boolean: !include_dir_merge_named input_boolean
# input_select: !include_dir_merge_named input_select
# input_slider: !include_dir_merge_named input_slider
panel_iframe: !include_dir_merge_named panel_iframe
# shell_command: !include_dir_merge_named shell_command
script: !include_dir_merge_named script




