
- platform: mqtt
  name: "Garage Temperature"
  state_topic: '1/101/51/51344/dht11/'
  unit_of_measurement: '°C'

- platform: mqtt  
  state_topic: '1/101/51/51344/dht11/'
  name: "Garage Humidity"
  unit_of_measurement: '%'
  
# sensor 1:
  # platform: mqtt
  # state_topic: '1/101/51/51344/dht11/'
  # name: 'Temperature'
  # unit_of_measurement: '°C'
  # value_template: '{{ value_json.temperature }}'

# sensor 2:
  # platform: mqtt
  # state_topic: '1/101/51/51332/dht11/'
  # name: 'Humidity'
  # unit_of_measurement: '%'
  # value_template: '{{ value_json.humidity }}'  