- platform: mqtt
  state_topic: "1/101/51/511123/reedswitch"
  command_topic: "1/101/51/511123/reedswitch"
  name: "Garage_Reed_Switch1_Status"
  qos: 0
  retain: true
  state_open: "open"
  state_closed: "closed"
  service_open: "1"
  service_close: "0"
  value_template: '{{ value }}'
  optimistic: true
  
